### ISSUE TITLE
[BUG] Boss rocket kills player with 1 hit

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/ghost-of-kyiv#135]
**Describe the bug**
Boss rocket kills player with 1 hit

**To Reproduce**
1. Complete 1st and 2nd level
2. On 3rd level, get hit by boss rocket, while you have 100 hp
3. You lose

**Expected behavior**
Boss rocket damage should be less than 100. For example make boss rocket damage `30`.

**Comment by 19thanks96** [comment]
))
