### ISSUE TITLE
Add 10 enemies

### ISSUE THREAD

**Issue by DarthVanger** [DarthVanger/ghost-of-kyiv#79]
## Add enemies in `index.html`

Add enemy images in `index.html`, just like we have 3 enemy images there already.

## Add enemies in `enemy.js`

We have `enemies` array in `enemy.js` file: https://github.com/DarthVanger/ghost-of-kyiv/blob/master/enemy.js#L39

```
export let enemies = [enemy1, enemy2, enemy3];
```

Add 7 more enemy objects and add them to the array:

```
let enemy4 = { 
  x: 2500,
  y: 200,
  width: 100,
  height: 100,
  ...
};

let enemy5 = { ... };
let enemy6 = { ... };

export let enemies = [enemy1, enemy2, enemy3, enemy4, enemy5, enemy6];
```

Adding enemies to the array should make them fly and add HP, and react to collisions and gatling gun, and rockets.

**Comment by DarthVanger** [comment]
### Add enemies in `index.html`

Add enemy images in `index.html`, just like we have 3 enemy images there already.

### Add enemies in `enemy.js`

We have `enemies` array in `enemy.js` file: https://github.com/DarthVanger/ghost-of-kyiv/blob/master/enemy.js#L39

```
export let enemies = [enemy1, enemy2, enemy3];
```

Add 7 more enemy objects and add them to the array:

```
let enemy4 = { 
  x: 2500,
  y: 200,
  width: 100,
  height: 100,
  ...
};

let enemy5 = { ... };
let enemy6 = { ... };

export let enemies = [enemy1, enemy2, enemy3, enemy4, enemy5, enemy6];
```

Adding enemies to the array should make them fly and add HP, and react to collisions and gatling gun, and rockets.

**Comment by 19thanks96** [comment]
I will create 10 enemies with 'for' loop
