### ISSUE TITLE
Split app.js into multiple files

### ISSUE THREAD

**Issue by 19thanks96** [DarthVanger/ghost-of-kyiv#91]

**Comment by DarthVanger** [comment]
[app.js](https://github.com/DarthVanger/ghost-of-kyiv/blob/40a4d1657306472d5c3b268eee922298538be4bf/app.js) is now only 34 lines long :)

![Image](https://user-images.githubusercontent.com/6686679/232323878-0ca0fa40-1f1b-49b4-9fed-7adf443dcdeb.png)
