### ISSUE TITLE
change gatling: add bullets with vx, vy and collision

### ISSUE THREAD

**Issue by 19thanks96** [DarthVanger/ghost-of-kyiv#94]
- [x] bullet img:  https://github.com/DarthVanger/ghost-of-kyiv/blob/master/img/Bullet_h100px.gif 
- [x] add control to fire bullets (keyboard 'space' key)
- [x] create func to fire bullets with horizontally plane and small (random) deviation
- [x] create obj - bullet 
- [x] create  `function moveBullet() {}`
- [x] create `function renderBullet() {}`
- [x]  instead of subtructing hp onclick, HP should be subtructed on collision with bullet img

**Comment by DarthVanger** [comment]
@19thanks96 What do you want to do exactly with gatling?
Chat what concretely?
Please explain.
